### ISSUE TITLE
Theme color pallet not fully showing

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/basketball#2]
The color pallets for the themes following options do not fully appear :
Theme Color : https://prnt.sc/uz36jf
Hover Color : https://prnt.sc/uz36ss
Button border Color : https://prnt.sc/uz371a

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
